import { test, expect } from '@playwright/test';
import { mockBackend, login, tinyPng, publicId } from './fixtures.js';

test('portal links to support; unconfigured admin fails closed', async ({page}) => {
  await page.goto('/'); await page.getByRole('link').filter({has:page.getByRole('heading',{name:'Yardım Merkezi',exact:true})}).click();
  await expect(page.getByText('Yardım merkezimiz hazırlanıyor')).toBeVisible();
  await page.getByRole('link',{name:'Yönetici girişi'}).click();
  await expect(page.locator('#setupNotice')).toBeVisible();
  await expect(page.getByRole('button',{name:'Giriş yap →',exact:true})).toBeDisabled();
});
test('search, category, video-first article and mobile layout', async ({page}) => {
  await mockBackend(page);
  const errors=[]; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/Destek/');
  await expect(page.locator('.article-row')).toHaveCount(2);
  await page.getByRole('searchbox').fill('sifre'); await expect(page.locator('.article-row')).toHaveCount(1);
  await page.locator('.article-row').click();
  await expect(page.locator('#articleContent h1')).toHaveText('Kullanıcı adı ve şifre nasıl değiştirilir?');
  const video = await page.locator('.article-video').boundingBox(); const title = await page.locator('#articleContent h1').boundingBox();
  expect(video.y).toBeLessThan(title.y);
  await expect(page.locator('#toc a')).toHaveCount(2);
  await expect(page.locator('.article-body img')).toHaveAttribute('src',/token=test/);
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/article-mobile.png',fullPage:true});
  await page.goto('/Destek/'); await page.getByRole('button',{name:/Kurulum & Başlangıç/}).click();
  await expect(page.locator('.article-row')).toHaveCount(1);
  await expect(page.locator('.article-row')).toContainText('Kart okuyucu');
  expect(errors).toEqual([]);
});
test('HTML from backend is sanitized and draft URL does not reveal a draft', async ({page}) => {
  const state = await mockBackend(page);
  state.articles[0].content_html = '<h2>Güvenli başlık</h2><img src=x onerror="window.pwned=1"><script>window.pwned=1</script><a href="javascript:alert(1)">Kötü bağlantı</a><iframe src="https://evil.test"></iframe><p onclick="window.pwned=1">Metin</p>';
  await page.goto('/Destek/?yazi=kullanici-adi-ve-sifre');
  await expect(page.locator('.article-body h2')).toBeVisible();
  await expect(page.locator('.article-body script,.article-body iframe,.article-body [onerror],.article-body [onclick]')).toHaveCount(0);
  await expect(page.locator('.article-body a')).not.toHaveAttribute('href',/javascript/);
  expect(await page.evaluate(() => window.pwned)).toBeUndefined();
  await page.goto('/Destek/?yazi=gizli-taslak'); await expect(page.getByRole('heading',{name:'Bu rehber bulunamadı'})).toBeVisible();
});
test('non-admin account cannot enter the dashboard', async ({page}) => {
  await mockBackend(page,{admin:false}); await login(page);
  await expect(page.locator('#loginStatus')).toContainText('yetkisi yok');
  await expect(page.locator('#dashboardView')).toBeHidden();
});
test('owner authors rich text, uploads image, saves draft, publishes, edits and deletes', async ({page}) => {
  const state = await mockBackend(page); page.on('dialog',dialog=>dialog.accept());
  await login(page); await expect(page.locator('#dashboardView')).toBeVisible();
  await page.getByRole('button',{name:'+ Yeni yazı oluştur',exact:true}).click();
  await page.getByLabel('Yazı başlığı', {exact:true}).fill('Şifre Değiştirme Rehberi');
  await expect(page.locator('#articleSlug')).toHaveValue('sifre-degistirme-rehberi');
  await page.locator('#articleCategory').selectOption({label:'Hesap & Kullanıcı'});
  await page.getByLabel('Kısa açıklama', {exact:true}).fill('Hesap bilgilerinizi düzenleme adımları.');
  await page.getByRole('button',{name:'Devam et →',exact:true}).click();
  await page.locator('#youtubeUrl').fill('https://youtu.be/abcdefghijk');
  await page.locator('.ql-editor').fill('Önce kullanıcı ayarlarınızı açın.');
  await page.locator('.ql-editor').press('ControlOrMeta+a');
  await page.getByRole('button',{name:'Kalın',exact:true}).click();
  await expect(page.locator('.ql-editor strong')).toContainText('kullanıcı');
  await page.getByRole('button',{name:'+ Adım başlığı',exact:true}).click();
  await page.locator('#imageFile').setInputFiles({name:'ekran.png',mimeType:'image/png',buffer:tinyPng});
  await page.getByLabel('Görsel açıklaması').fill('Kullanıcı ayarları ekranı');
  await page.getByRole('button',{name:'Yükle ve yazıya ekle'}).click();
  await expect(page.locator('.ql-editor img')).toHaveAttribute('alt','Kullanıcı ayarları ekranı');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/editor-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1080});
  await page.screenshot({path:'test-results/editor-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Önizleme ↗',exact:true}).click();
  await expect(page.locator('#previewDialog .article-video')).toBeVisible();
  await expect(page.locator('#previewDialog img')).toHaveAttribute('alt','Kullanıcı ayarları ekranı');
  await page.getByRole('button',{name:'Kapat',exact:true}).click();
  await page.getByRole('button',{name:'Devam et →',exact:true}).click();
  await page.getByRole('button',{name:'Taslak olarak kaydet',exact:true}).click();
  await expect(page.locator('#editorStatus')).toContainText('Taslak kaydedildi');
  let saved = state.articles.find(a=>a.slug==='sifre-degistirme-rehberi');
  expect(saved.status).toBe('draft'); expect(saved.content_html).toContain('<strong>'); expect(saved.content_html).not.toContain('token=test');
  expect(state.uploaded.length).toBe(1);
  await page.getByRole('button',{name:'Yayınla →',exact:true}).click();
  await expect(page.locator('#editorStatus')).toContainText('Yazı yayınlandı');
  expect(saved.status).toBe('published');
  await page.getByRole('button',{name:'← Yazılara dön',exact:true}).click();
  await page.getByRole('button',{name:'Şifre Değiştirme Rehberi yazısını düzenle',exact:true}).click();
  await expect(page.locator('#articleTitle')).toHaveValue('Şifre Değiştirme Rehberi');
  await page.getByRole('button',{name:'← Yazılara dön',exact:true}).click();
  await page.getByRole('button',{name:'Şifre Değiştirme Rehberi yazısını sil',exact:true}).click();
  await expect(page.getByRole('button',{name:'Şifre Değiştirme Rehberi yazısını düzenle',exact:true})).toHaveCount(0);
  expect(state.articles.find(a=>a.slug==='sifre-degistirme-rehberi')).toBeUndefined();
});
test('categories can be created and edited; unsaved editor survives reload', async ({page}) => {
  const state = await mockBackend(page); await login(page);
  await page.getByRole('button',{name:'Kategorileri yönet',exact:true}).click();
  await page.getByLabel('Kategori adı', {exact:true}).fill('Ödemeler');
  await page.getByRole('button',{name:'Kategoriyi kaydet',exact:true}).click();
  await expect(page.locator('#categoryManager')).toContainText('Ödemeler');
  await page.locator('.category-item').filter({hasText:'Ödemeler'}).getByRole('button',{name:'Düzenle'}).click();
  await page.getByLabel('Kategori adı', {exact:true}).fill('Ödeme İşlemleri');
  await page.getByRole('button',{name:'Kategoriyi kaydet',exact:true}).click();
  await expect(page.locator('#categoryManager')).toContainText('Ödeme İşlemleri');
  await page.getByRole('button',{name:'Pencereyi kapat',exact:true}).click();
  await page.getByRole('button',{name:'+ Yeni yazı oluştur',exact:true}).click();
  await page.getByLabel('Yazı başlığı', {exact:true}).fill('Kaybolmayan taslak');
  await expect(page.locator('#saveState')).toContainText('Oturumda yedeklendi');
  page.on('dialog',dialog=>dialog.accept()); await page.reload();
  await expect(page.locator('#restoreNotice')).toBeVisible();
  await page.getByRole('button',{name:'Düzenlemeye devam et',exact:true}).click();
  await expect(page.getByLabel('Yazı başlığı',{exact:true})).toHaveValue('Kaybolmayan taslak');
  expect(state.categories.some(c=>c.name==='Ödeme İşlemleri')).toBe(true);
});
test('API errors have a retry path and desktop design fits viewport', async ({page}) => {
  await mockBackend(page,{fail:true}); await page.goto('/Destek/');
  await expect(page.getByRole('button',{name:'Tekrar dene'})).toBeVisible({timeout:20000});
});
test('desktop help center screenshot', async ({page}) => {
  await mockBackend(page); await page.setViewportSize({width:1440,height:1080}); await page.goto('/Destek/');
  await expect(page.locator('.article-row')).toHaveCount(2); await page.screenshot({path:'test-results/help-desktop.png',fullPage:true});
});
