import { build } from 'esbuild';
import { mkdir, copyFile, readFile, readdir, writeFile } from 'node:fs/promises';
await mkdir('Destek/assets', { recursive: true });
await build({
  entryPoints: { public: 'Destek/src/public.js', admin: 'Destek/src/admin.js' },
  outdir: 'Destek/assets', bundle: true, minify: true, format: 'esm',
  splitting: true, target: ['es2022'], legalComments: 'linked',
});
await copyFile('node_modules/quill/dist/quill.snow.css', 'Destek/assets/quill.snow.css');
await build({
  entryPoints: ['RaspberryManager/src/auth.js'], outfile: 'RaspberryManager/assets/auth.js',
  bundle: true, minify: true, format: 'esm', target: ['es2022'], legalComments: 'linked',
});
const lock = JSON.parse(await readFile('package-lock.json', 'utf8'));
const notices = ['Third-party package licenses — generated by scripts/build.mjs'];
for (const [path, info] of Object.entries(lock.packages)) {
  if (!path || info.dev) continue;
  const files = (await readdir(path, { withFileTypes: true })).filter(file => file.isFile() && /^(licen[sc]e|copying)/i.test(file.name));
  for (const file of files) notices.push(`\n${'='.repeat(72)}\n${path} @ ${info.version}\n${file.name}\n\n${await readFile(`${path}/${file.name}`, 'utf8')}`);
}
await writeFile('Destek/assets/THIRD-PARTY-NOTICES.txt', notices.join('\n'));
console.log('Destek merkezi hazır: Destek/assets');
